
/*
Auto-generated by CVXPYgen on January 03, 2026 at 23:30:15.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_ref(0, -0.79394600800439707466);
  cpg_update_x0(0, -1.46406581592790474566);
  cpg_update_A(0, -1.08161232409998042669);
  cpg_update_B(0, 1.17377740094623916889);
  cpg_update_d(0, 2.57483517604654865707);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<124; i++) {
    printf("x[%d] = %f\n", i, CPG_Result.prim->x[i]);
  }
  for(i=0; i<60; i++) {
    printf("u[%d] = %f\n", i, CPG_Result.prim->u[i]);
  }

  // Print dual solution
  for(i=0; i<4; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<4; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<2; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<2; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  for(i=0; i<4; i++) {
    printf("d4[%d] = %f\n", i, CPG_Result.dual->d4[i]);
  }
  for(i=0; i<2; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  for(i=0; i<2; i++) {
    printf("d6[%d] = %f\n", i, CPG_Result.dual->d6[i]);
  }
  for(i=0; i<4; i++) {
    printf("d7[%d] = %f\n", i, CPG_Result.dual->d7[i]);
  }
  for(i=0; i<2; i++) {
    printf("d8[%d] = %f\n", i, CPG_Result.dual->d8[i]);
  }
  for(i=0; i<2; i++) {
    printf("d9[%d] = %f\n", i, CPG_Result.dual->d9[i]);
  }
  for(i=0; i<4; i++) {
    printf("d10[%d] = %f\n", i, CPG_Result.dual->d10[i]);
  }
  for(i=0; i<2; i++) {
    printf("d11[%d] = %f\n", i, CPG_Result.dual->d11[i]);
  }
  for(i=0; i<2; i++) {
    printf("d12[%d] = %f\n", i, CPG_Result.dual->d12[i]);
  }
  for(i=0; i<4; i++) {
    printf("d13[%d] = %f\n", i, CPG_Result.dual->d13[i]);
  }
  for(i=0; i<2; i++) {
    printf("d14[%d] = %f\n", i, CPG_Result.dual->d14[i]);
  }
  for(i=0; i<2; i++) {
    printf("d15[%d] = %f\n", i, CPG_Result.dual->d15[i]);
  }
  for(i=0; i<4; i++) {
    printf("d16[%d] = %f\n", i, CPG_Result.dual->d16[i]);
  }
  for(i=0; i<2; i++) {
    printf("d17[%d] = %f\n", i, CPG_Result.dual->d17[i]);
  }
  for(i=0; i<2; i++) {
    printf("d18[%d] = %f\n", i, CPG_Result.dual->d18[i]);
  }
  for(i=0; i<4; i++) {
    printf("d19[%d] = %f\n", i, CPG_Result.dual->d19[i]);
  }
  for(i=0; i<2; i++) {
    printf("d20[%d] = %f\n", i, CPG_Result.dual->d20[i]);
  }
  for(i=0; i<2; i++) {
    printf("d21[%d] = %f\n", i, CPG_Result.dual->d21[i]);
  }
  for(i=0; i<4; i++) {
    printf("d22[%d] = %f\n", i, CPG_Result.dual->d22[i]);
  }
  for(i=0; i<2; i++) {
    printf("d23[%d] = %f\n", i, CPG_Result.dual->d23[i]);
  }
  for(i=0; i<2; i++) {
    printf("d24[%d] = %f\n", i, CPG_Result.dual->d24[i]);
  }
  for(i=0; i<4; i++) {
    printf("d25[%d] = %f\n", i, CPG_Result.dual->d25[i]);
  }
  for(i=0; i<2; i++) {
    printf("d26[%d] = %f\n", i, CPG_Result.dual->d26[i]);
  }
  for(i=0; i<2; i++) {
    printf("d27[%d] = %f\n", i, CPG_Result.dual->d27[i]);
  }
  for(i=0; i<4; i++) {
    printf("d28[%d] = %f\n", i, CPG_Result.dual->d28[i]);
  }
  for(i=0; i<2; i++) {
    printf("d29[%d] = %f\n", i, CPG_Result.dual->d29[i]);
  }
  for(i=0; i<2; i++) {
    printf("d30[%d] = %f\n", i, CPG_Result.dual->d30[i]);
  }
  for(i=0; i<4; i++) {
    printf("d31[%d] = %f\n", i, CPG_Result.dual->d31[i]);
  }
  for(i=0; i<2; i++) {
    printf("d32[%d] = %f\n", i, CPG_Result.dual->d32[i]);
  }
  for(i=0; i<2; i++) {
    printf("d33[%d] = %f\n", i, CPG_Result.dual->d33[i]);
  }
  for(i=0; i<4; i++) {
    printf("d34[%d] = %f\n", i, CPG_Result.dual->d34[i]);
  }
  for(i=0; i<2; i++) {
    printf("d35[%d] = %f\n", i, CPG_Result.dual->d35[i]);
  }
  for(i=0; i<2; i++) {
    printf("d36[%d] = %f\n", i, CPG_Result.dual->d36[i]);
  }
  for(i=0; i<4; i++) {
    printf("d37[%d] = %f\n", i, CPG_Result.dual->d37[i]);
  }
  for(i=0; i<2; i++) {
    printf("d38[%d] = %f\n", i, CPG_Result.dual->d38[i]);
  }
  for(i=0; i<2; i++) {
    printf("d39[%d] = %f\n", i, CPG_Result.dual->d39[i]);
  }
  for(i=0; i<4; i++) {
    printf("d40[%d] = %f\n", i, CPG_Result.dual->d40[i]);
  }
  for(i=0; i<2; i++) {
    printf("d41[%d] = %f\n", i, CPG_Result.dual->d41[i]);
  }
  for(i=0; i<2; i++) {
    printf("d42[%d] = %f\n", i, CPG_Result.dual->d42[i]);
  }
  for(i=0; i<4; i++) {
    printf("d43[%d] = %f\n", i, CPG_Result.dual->d43[i]);
  }
  for(i=0; i<2; i++) {
    printf("d44[%d] = %f\n", i, CPG_Result.dual->d44[i]);
  }
  for(i=0; i<2; i++) {
    printf("d45[%d] = %f\n", i, CPG_Result.dual->d45[i]);
  }
  for(i=0; i<4; i++) {
    printf("d46[%d] = %f\n", i, CPG_Result.dual->d46[i]);
  }
  for(i=0; i<2; i++) {
    printf("d47[%d] = %f\n", i, CPG_Result.dual->d47[i]);
  }
  for(i=0; i<2; i++) {
    printf("d48[%d] = %f\n", i, CPG_Result.dual->d48[i]);
  }
  for(i=0; i<4; i++) {
    printf("d49[%d] = %f\n", i, CPG_Result.dual->d49[i]);
  }
  for(i=0; i<2; i++) {
    printf("d50[%d] = %f\n", i, CPG_Result.dual->d50[i]);
  }
  for(i=0; i<2; i++) {
    printf("d51[%d] = %f\n", i, CPG_Result.dual->d51[i]);
  }
  for(i=0; i<4; i++) {
    printf("d52[%d] = %f\n", i, CPG_Result.dual->d52[i]);
  }
  for(i=0; i<2; i++) {
    printf("d53[%d] = %f\n", i, CPG_Result.dual->d53[i]);
  }
  for(i=0; i<2; i++) {
    printf("d54[%d] = %f\n", i, CPG_Result.dual->d54[i]);
  }
  for(i=0; i<4; i++) {
    printf("d55[%d] = %f\n", i, CPG_Result.dual->d55[i]);
  }
  for(i=0; i<2; i++) {
    printf("d56[%d] = %f\n", i, CPG_Result.dual->d56[i]);
  }
  for(i=0; i<2; i++) {
    printf("d57[%d] = %f\n", i, CPG_Result.dual->d57[i]);
  }
  for(i=0; i<4; i++) {
    printf("d58[%d] = %f\n", i, CPG_Result.dual->d58[i]);
  }
  for(i=0; i<2; i++) {
    printf("d59[%d] = %f\n", i, CPG_Result.dual->d59[i]);
  }
  for(i=0; i<2; i++) {
    printf("d60[%d] = %f\n", i, CPG_Result.dual->d60[i]);
  }
  for(i=0; i<4; i++) {
    printf("d61[%d] = %f\n", i, CPG_Result.dual->d61[i]);
  }
  for(i=0; i<2; i++) {
    printf("d62[%d] = %f\n", i, CPG_Result.dual->d62[i]);
  }
  for(i=0; i<2; i++) {
    printf("d63[%d] = %f\n", i, CPG_Result.dual->d63[i]);
  }
  for(i=0; i<4; i++) {
    printf("d64[%d] = %f\n", i, CPG_Result.dual->d64[i]);
  }
  for(i=0; i<2; i++) {
    printf("d65[%d] = %f\n", i, CPG_Result.dual->d65[i]);
  }
  for(i=0; i<2; i++) {
    printf("d66[%d] = %f\n", i, CPG_Result.dual->d66[i]);
  }
  for(i=0; i<4; i++) {
    printf("d67[%d] = %f\n", i, CPG_Result.dual->d67[i]);
  }
  for(i=0; i<2; i++) {
    printf("d68[%d] = %f\n", i, CPG_Result.dual->d68[i]);
  }
  for(i=0; i<2; i++) {
    printf("d69[%d] = %f\n", i, CPG_Result.dual->d69[i]);
  }
  for(i=0; i<4; i++) {
    printf("d70[%d] = %f\n", i, CPG_Result.dual->d70[i]);
  }
  for(i=0; i<2; i++) {
    printf("d71[%d] = %f\n", i, CPG_Result.dual->d71[i]);
  }
  for(i=0; i<2; i++) {
    printf("d72[%d] = %f\n", i, CPG_Result.dual->d72[i]);
  }
  for(i=0; i<4; i++) {
    printf("d73[%d] = %f\n", i, CPG_Result.dual->d73[i]);
  }
  for(i=0; i<2; i++) {
    printf("d74[%d] = %f\n", i, CPG_Result.dual->d74[i]);
  }
  for(i=0; i<2; i++) {
    printf("d75[%d] = %f\n", i, CPG_Result.dual->d75[i]);
  }
  for(i=0; i<4; i++) {
    printf("d76[%d] = %f\n", i, CPG_Result.dual->d76[i]);
  }
  for(i=0; i<2; i++) {
    printf("d77[%d] = %f\n", i, CPG_Result.dual->d77[i]);
  }
  for(i=0; i<2; i++) {
    printf("d78[%d] = %f\n", i, CPG_Result.dual->d78[i]);
  }
  for(i=0; i<4; i++) {
    printf("d79[%d] = %f\n", i, CPG_Result.dual->d79[i]);
  }
  for(i=0; i<2; i++) {
    printf("d80[%d] = %f\n", i, CPG_Result.dual->d80[i]);
  }
  for(i=0; i<2; i++) {
    printf("d81[%d] = %f\n", i, CPG_Result.dual->d81[i]);
  }
  for(i=0; i<4; i++) {
    printf("d82[%d] = %f\n", i, CPG_Result.dual->d82[i]);
  }
  for(i=0; i<2; i++) {
    printf("d83[%d] = %f\n", i, CPG_Result.dual->d83[i]);
  }
  for(i=0; i<2; i++) {
    printf("d84[%d] = %f\n", i, CPG_Result.dual->d84[i]);
  }
  for(i=0; i<4; i++) {
    printf("d85[%d] = %f\n", i, CPG_Result.dual->d85[i]);
  }
  for(i=0; i<2; i++) {
    printf("d86[%d] = %f\n", i, CPG_Result.dual->d86[i]);
  }
  for(i=0; i<2; i++) {
    printf("d87[%d] = %f\n", i, CPG_Result.dual->d87[i]);
  }
  for(i=0; i<4; i++) {
    printf("d88[%d] = %f\n", i, CPG_Result.dual->d88[i]);
  }
  for(i=0; i<2; i++) {
    printf("d89[%d] = %f\n", i, CPG_Result.dual->d89[i]);
  }
  for(i=0; i<2; i++) {
    printf("d90[%d] = %f\n", i, CPG_Result.dual->d90[i]);
  }

  return 0;

}
