/*
 * Copyright 2026 Adilkhan Salkimbayev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was autogenerated by OSQP on Sat Jan  3 23:30:14 2026
 * 
 * This file contains the prototype for the solver structure needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#ifndef WORKSPACE_H
#define WORKSPACE_H

#include "osqp_api_types.h"

#ifdef __cplusplus
extern "C" {
#endif

  extern OSQPSolver solver;
  extern OSQPFloat sol_x[364];
  extern OSQPFloat sol_y[424];

#ifdef __cplusplus
}
#endif

#endif /* ifndef WORKSPACE_H */
