/*
 * Copyright 2026 Adilkhan Salkimbayev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/*
Auto-generated by CVXPYgen on January 03, 2026 at 23:30:15.
Content: Function declarations.
*/

#include "cpg_workspace.h"

// Update user-defined parameter values
extern void cpg_update_ref(cpg_int idx, cpg_float val);
extern void cpg_update_x0(cpg_int idx, cpg_float val);
extern void cpg_update_A(cpg_int idx, cpg_float val);
extern void cpg_update_B(cpg_int idx, cpg_float val);
extern void cpg_update_d(cpg_int idx, cpg_float val);

// Map user-defined to canonical parameters
extern void cpg_canonicalize_A();
extern void cpg_canonicalize_l();
extern void cpg_canonicalize_u();

// Retrieve solver information
extern void cpg_retrieve_info();

// Solve via canonicalization, canonical solve, retrieval
extern void cpg_solve();

// Update solver settings
extern void cpg_set_solver_default_settings();
extern void cpg_set_solver_max_iter(cpg_int max_iter_new);
extern void cpg_set_solver_eps_abs(cpg_float eps_abs_new);
extern void cpg_set_solver_eps_rel(cpg_float eps_rel_new);
extern void cpg_set_solver_eps_prim_inf(cpg_float eps_prim_inf_new);
extern void cpg_set_solver_eps_dual_inf(cpg_float eps_dual_inf_new);
extern void cpg_set_solver_scaled_termination(cpg_int scaled_termination_new);
extern void cpg_set_solver_check_termination(cpg_int check_termination_new);
extern void cpg_set_solver_warm_starting(cpg_int warm_starting_new);
