
"""
Auto-generated by CVXPYgen on January 03, 2026 at 23:30:15.
Content: Custom solve method for CVXPY interface.
"""

import time
import warnings
import numpy as np
from cvxpy.reductions import Solution
from cvxpy.problems.problem import SolverStats
from Nucleo_MPC_GenFinal import cpg_module


standard_settings_names = {'warm_start': 'warm_starting'}


def squeeze_scalar(val):
    if isinstance(val, np.ndarray):
        val = val.squeeze()
        if val.shape == ():
            return val.item()
    return val


def cpg_solve(prob, updated_params=None, **kwargs):

    # set flags for updated parameters
    upd = cpg_module.cpg_updated()
    if updated_params is None:
        updated_params = ["ref", "x0", "A", "B", "d"]
    for p in updated_params:
        try:
            setattr(upd, p, True)
        except AttributeError:
            raise AttributeError(f"{p} is not a parameter.")

    # set solver settings
    cpg_module.set_solver_default_settings()
    for key, value in kwargs.items():
        try:
            eval(f'cpg_module.set_solver_{standard_settings_names.get(key, key)}(value)')
        except AttributeError:
            raise AttributeError(f'Solver setting "{key}" not available.')

    # set parameter values
    par = cpg_module.cpg_params()
    param_dict = prob.param_dict
    par.ref = list(param_dict["ref"].value.flatten(order="F"))
    par.x0 = list(param_dict["x0"].value.flatten(order="F"))
    par.A = list(param_dict["A"].value.flatten(order="F"))
    par.B = list(param_dict["B"].value.flatten(order="F"))
    par.d = list(param_dict["d"].value.flatten(order="F"))

    # solve
    t0 = time.time()
    res = cpg_module.solve(upd, par)
    t1 = time.time()

    # store solution in problem object
    prob._clear_solution()
    prob.var_dict['x'].save_value(np.array(res.cpg_prim.x).reshape((4, 31), order='F'))
    prob.var_dict['u'].save_value(np.array(res.cpg_prim.u).reshape((2, 30), order='F'))
    prob.constraints[0].save_dual_value(np.array(res.cpg_dual.d0).reshape((4,), order='F'))
    prob.constraints[1].save_dual_value(np.array(res.cpg_dual.d1).reshape((4,), order='F'))
    prob.constraints[2].save_dual_value(np.array(res.cpg_dual.d2).reshape((2,), order='F'))
    prob.constraints[3].save_dual_value(np.array(res.cpg_dual.d3).reshape((2,), order='F'))
    prob.constraints[4].save_dual_value(np.array(res.cpg_dual.d4).reshape((4,), order='F'))
    prob.constraints[5].save_dual_value(np.array(res.cpg_dual.d5).reshape((2,), order='F'))
    prob.constraints[6].save_dual_value(np.array(res.cpg_dual.d6).reshape((2,), order='F'))
    prob.constraints[7].save_dual_value(np.array(res.cpg_dual.d7).reshape((4,), order='F'))
    prob.constraints[8].save_dual_value(np.array(res.cpg_dual.d8).reshape((2,), order='F'))
    prob.constraints[9].save_dual_value(np.array(res.cpg_dual.d9).reshape((2,), order='F'))
    prob.constraints[10].save_dual_value(np.array(res.cpg_dual.d10).reshape((4,), order='F'))
    prob.constraints[11].save_dual_value(np.array(res.cpg_dual.d11).reshape((2,), order='F'))
    prob.constraints[12].save_dual_value(np.array(res.cpg_dual.d12).reshape((2,), order='F'))
    prob.constraints[13].save_dual_value(np.array(res.cpg_dual.d13).reshape((4,), order='F'))
    prob.constraints[14].save_dual_value(np.array(res.cpg_dual.d14).reshape((2,), order='F'))
    prob.constraints[15].save_dual_value(np.array(res.cpg_dual.d15).reshape((2,), order='F'))
    prob.constraints[16].save_dual_value(np.array(res.cpg_dual.d16).reshape((4,), order='F'))
    prob.constraints[17].save_dual_value(np.array(res.cpg_dual.d17).reshape((2,), order='F'))
    prob.constraints[18].save_dual_value(np.array(res.cpg_dual.d18).reshape((2,), order='F'))
    prob.constraints[19].save_dual_value(np.array(res.cpg_dual.d19).reshape((4,), order='F'))
    prob.constraints[20].save_dual_value(np.array(res.cpg_dual.d20).reshape((2,), order='F'))
    prob.constraints[21].save_dual_value(np.array(res.cpg_dual.d21).reshape((2,), order='F'))
    prob.constraints[22].save_dual_value(np.array(res.cpg_dual.d22).reshape((4,), order='F'))
    prob.constraints[23].save_dual_value(np.array(res.cpg_dual.d23).reshape((2,), order='F'))
    prob.constraints[24].save_dual_value(np.array(res.cpg_dual.d24).reshape((2,), order='F'))
    prob.constraints[25].save_dual_value(np.array(res.cpg_dual.d25).reshape((4,), order='F'))
    prob.constraints[26].save_dual_value(np.array(res.cpg_dual.d26).reshape((2,), order='F'))
    prob.constraints[27].save_dual_value(np.array(res.cpg_dual.d27).reshape((2,), order='F'))
    prob.constraints[28].save_dual_value(np.array(res.cpg_dual.d28).reshape((4,), order='F'))
    prob.constraints[29].save_dual_value(np.array(res.cpg_dual.d29).reshape((2,), order='F'))
    prob.constraints[30].save_dual_value(np.array(res.cpg_dual.d30).reshape((2,), order='F'))
    prob.constraints[31].save_dual_value(np.array(res.cpg_dual.d31).reshape((4,), order='F'))
    prob.constraints[32].save_dual_value(np.array(res.cpg_dual.d32).reshape((2,), order='F'))
    prob.constraints[33].save_dual_value(np.array(res.cpg_dual.d33).reshape((2,), order='F'))
    prob.constraints[34].save_dual_value(np.array(res.cpg_dual.d34).reshape((4,), order='F'))
    prob.constraints[35].save_dual_value(np.array(res.cpg_dual.d35).reshape((2,), order='F'))
    prob.constraints[36].save_dual_value(np.array(res.cpg_dual.d36).reshape((2,), order='F'))
    prob.constraints[37].save_dual_value(np.array(res.cpg_dual.d37).reshape((4,), order='F'))
    prob.constraints[38].save_dual_value(np.array(res.cpg_dual.d38).reshape((2,), order='F'))
    prob.constraints[39].save_dual_value(np.array(res.cpg_dual.d39).reshape((2,), order='F'))
    prob.constraints[40].save_dual_value(np.array(res.cpg_dual.d40).reshape((4,), order='F'))
    prob.constraints[41].save_dual_value(np.array(res.cpg_dual.d41).reshape((2,), order='F'))
    prob.constraints[42].save_dual_value(np.array(res.cpg_dual.d42).reshape((2,), order='F'))
    prob.constraints[43].save_dual_value(np.array(res.cpg_dual.d43).reshape((4,), order='F'))
    prob.constraints[44].save_dual_value(np.array(res.cpg_dual.d44).reshape((2,), order='F'))
    prob.constraints[45].save_dual_value(np.array(res.cpg_dual.d45).reshape((2,), order='F'))
    prob.constraints[46].save_dual_value(np.array(res.cpg_dual.d46).reshape((4,), order='F'))
    prob.constraints[47].save_dual_value(np.array(res.cpg_dual.d47).reshape((2,), order='F'))
    prob.constraints[48].save_dual_value(np.array(res.cpg_dual.d48).reshape((2,), order='F'))
    prob.constraints[49].save_dual_value(np.array(res.cpg_dual.d49).reshape((4,), order='F'))
    prob.constraints[50].save_dual_value(np.array(res.cpg_dual.d50).reshape((2,), order='F'))
    prob.constraints[51].save_dual_value(np.array(res.cpg_dual.d51).reshape((2,), order='F'))
    prob.constraints[52].save_dual_value(np.array(res.cpg_dual.d52).reshape((4,), order='F'))
    prob.constraints[53].save_dual_value(np.array(res.cpg_dual.d53).reshape((2,), order='F'))
    prob.constraints[54].save_dual_value(np.array(res.cpg_dual.d54).reshape((2,), order='F'))
    prob.constraints[55].save_dual_value(np.array(res.cpg_dual.d55).reshape((4,), order='F'))
    prob.constraints[56].save_dual_value(np.array(res.cpg_dual.d56).reshape((2,), order='F'))
    prob.constraints[57].save_dual_value(np.array(res.cpg_dual.d57).reshape((2,), order='F'))
    prob.constraints[58].save_dual_value(np.array(res.cpg_dual.d58).reshape((4,), order='F'))
    prob.constraints[59].save_dual_value(np.array(res.cpg_dual.d59).reshape((2,), order='F'))
    prob.constraints[60].save_dual_value(np.array(res.cpg_dual.d60).reshape((2,), order='F'))
    prob.constraints[61].save_dual_value(np.array(res.cpg_dual.d61).reshape((4,), order='F'))
    prob.constraints[62].save_dual_value(np.array(res.cpg_dual.d62).reshape((2,), order='F'))
    prob.constraints[63].save_dual_value(np.array(res.cpg_dual.d63).reshape((2,), order='F'))
    prob.constraints[64].save_dual_value(np.array(res.cpg_dual.d64).reshape((4,), order='F'))
    prob.constraints[65].save_dual_value(np.array(res.cpg_dual.d65).reshape((2,), order='F'))
    prob.constraints[66].save_dual_value(np.array(res.cpg_dual.d66).reshape((2,), order='F'))
    prob.constraints[67].save_dual_value(np.array(res.cpg_dual.d67).reshape((4,), order='F'))
    prob.constraints[68].save_dual_value(np.array(res.cpg_dual.d68).reshape((2,), order='F'))
    prob.constraints[69].save_dual_value(np.array(res.cpg_dual.d69).reshape((2,), order='F'))
    prob.constraints[70].save_dual_value(np.array(res.cpg_dual.d70).reshape((4,), order='F'))
    prob.constraints[71].save_dual_value(np.array(res.cpg_dual.d71).reshape((2,), order='F'))
    prob.constraints[72].save_dual_value(np.array(res.cpg_dual.d72).reshape((2,), order='F'))
    prob.constraints[73].save_dual_value(np.array(res.cpg_dual.d73).reshape((4,), order='F'))
    prob.constraints[74].save_dual_value(np.array(res.cpg_dual.d74).reshape((2,), order='F'))
    prob.constraints[75].save_dual_value(np.array(res.cpg_dual.d75).reshape((2,), order='F'))
    prob.constraints[76].save_dual_value(np.array(res.cpg_dual.d76).reshape((4,), order='F'))
    prob.constraints[77].save_dual_value(np.array(res.cpg_dual.d77).reshape((2,), order='F'))
    prob.constraints[78].save_dual_value(np.array(res.cpg_dual.d78).reshape((2,), order='F'))
    prob.constraints[79].save_dual_value(np.array(res.cpg_dual.d79).reshape((4,), order='F'))
    prob.constraints[80].save_dual_value(np.array(res.cpg_dual.d80).reshape((2,), order='F'))
    prob.constraints[81].save_dual_value(np.array(res.cpg_dual.d81).reshape((2,), order='F'))
    prob.constraints[82].save_dual_value(np.array(res.cpg_dual.d82).reshape((4,), order='F'))
    prob.constraints[83].save_dual_value(np.array(res.cpg_dual.d83).reshape((2,), order='F'))
    prob.constraints[84].save_dual_value(np.array(res.cpg_dual.d84).reshape((2,), order='F'))
    prob.constraints[85].save_dual_value(np.array(res.cpg_dual.d85).reshape((4,), order='F'))
    prob.constraints[86].save_dual_value(np.array(res.cpg_dual.d86).reshape((2,), order='F'))
    prob.constraints[87].save_dual_value(np.array(res.cpg_dual.d87).reshape((2,), order='F'))
    prob.constraints[88].save_dual_value(np.array(res.cpg_dual.d88).reshape((4,), order='F'))
    prob.constraints[89].save_dual_value(np.array(res.cpg_dual.d89).reshape((2,), order='F'))
    prob.constraints[90].save_dual_value(np.array(res.cpg_dual.d90).reshape((2,), order='F'))

    # store additional solver information in problem object
    prob._status = res.cpg_info.status
    if abs(res.cpg_info.obj_val) == 1e30:
        prob._value = np.sign(res.cpg_info.obj_val) * np.inf
    else:
        prob._value = res.cpg_info.obj_val
    primal_vars = {var.id: var.value for var in prob.variables()}
    dual_vars = {c.id: c.dual_value for c in prob.constraints}
    solver_specific_stats = {'obj_val': res.cpg_info.obj_val,
                             'status': prob._status,
                             'iter': res.cpg_info.iter,
                             'pri_res': res.cpg_info.pri_res,
                             'dua_res': res.cpg_info.dua_res,
                             'time': res.cpg_info.time}
    attr = {'solve_time': t1 - t0, 'solver_specific_stats': solver_specific_stats, 'num_iters': res.cpg_info.iter}
    prob._solution = Solution(prob.status, prob.value, primal_vars, dual_vars, attr)
    results_dict = {'solver_specific_stats': solver_specific_stats,
                    'num_iters': res.cpg_info.iter,
                    'solve_time': t1 - t0}
    prob._solver_stats = SolverStats.from_dict(results_dict, 'OSQP')

    return prob.value


