# Copyright 2026 Adilkhan Salkimbayev
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Stage 6 -- every figure in the manuscript, generated from the stored results.

Figures are written both into revision/figures/ and directly into the LaTeX
tree (els-cas-templates/figs/) so that the paper never contains a plot whose
data cannot be regenerated by running these scripts in order.
"""

from __future__ import annotations

import json
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

import qtlib as Q

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "results")
TRAJ = os.path.join(RES, "traj")
FIGS = os.path.join(HERE, "figures")
PAPER = os.path.abspath(os.path.join(HERE, "..", "..", "..", "els-cas-templates", "figs"))
os.makedirs(FIGS, exist_ok=True)

try:
    import scienceplots  # noqa: F401
    plt.style.use(["science", "ieee"])
except Exception:
    plt.style.use("seaborn-v0_8-paper")
plt.rcParams.update({
    "text.usetex": False,
    "font.family": "serif",
    "axes.grid": True,
    "grid.alpha": 0.25,
    "legend.fontsize": 6,
    "axes.labelsize": 8,
    "xtick.labelsize": 7,
    "ytick.labelsize": 7,
    "lines.linewidth": 1.0,
    "figure.dpi": 300,
})

STYLE = {
    "LTV-MPC": dict(color="black", ls="-"),
    "Symbolic KAN": dict(color="crimson", ls="--"),
    "MLP (32-32)": dict(color="tab:blue", ls="-."),
    "MLP (8)": dict(color="tab:cyan", ls=":"),
    "DeepONet": dict(color="tab:green", ls=":"),
    "Poly ridge (deg 2)": dict(color="tab:orange", ls=":"),
    "Poly ridge (deg 3)": dict(color="tab:brown", ls="-."),
    "Gain-scheduled LQR": dict(color="tab:purple", ls=(0, (3, 1, 1, 1))),
}
KEY = ["LTV-MPC", "Symbolic KAN", "MLP (32-32)", "Gain-scheduled LQR", "Poly ridge (deg 3)"]


def save(fig, name):
    for d in (FIGS, PAPER):
        if os.path.isdir(d):
            fig.savefig(os.path.join(d, name), bbox_inches="tight")
    plt.close(fig)
    print("  wrote", name, flush=True)


def slug(n):
    return n.replace(" ", "_").replace("(", "").replace(")", "")


def load_traj(tag, regime, name):
    p = os.path.join(TRAJ, f"{tag}_{regime}_{slug(name)}.npz")
    return np.load(p) if os.path.exists(p) else None


# ------------------------------------------------------------------ Fig A
def fig_tracking(regime="NMP"):
    fig, ax = plt.subplots(3, 1, figsize=(3.5, 4.2), sharex=True)
    for n in KEY:
        d = load_traj("S1", regime, n)
        if d is None:
            continue
        ax[0].plot(d["t"], d["x"][:, 0], label=n, **STYLE[n])
        ax[1].plot(d["t"], d["x"][:, 1], **STYLE[n])
        ax[2].plot(d["t"], d["u"][:, 0], **STYLE[n])
    ref = d["ref"][0]
    ax[0].axhline(ref[0], color="gray", ls=":", lw=0.8)
    ax[1].axhline(ref[1], color="gray", ls=":", lw=0.8)
    ax[0].set_ylabel(r"$h_1$ (cm)")
    ax[1].set_ylabel(r"$h_2$ (cm)")
    ax[2].set_ylabel(r"$u_1$ (V)")
    ax[2].set_xlabel("Time (s)")
    ax[0].legend(ncol=2, frameon=True, loc="upper right")
    fig.subplots_adjust(hspace=0.12)
    save(fig, f"Fig_Track_{regime}.pdf")


# ------------------------------------------------------------------ Fig B
def fig_complexity():
    d = json.load(open(os.path.join(RES, "sparsity_sweep.json")))
    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.4), sharey=False)
    for ax, reg in zip(axes, ("MP", "NMP")):
        k = d[reg]["kan_support_curve"]
        p = d[reg]["direct_polynomial_curve"]
        ax.plot([c["flops"] for c in k], [c["nmae"] for c in k], "o-",
                color="crimson", ms=3, label="KAN-selected support")
        ax.plot([c["flops"] for c in p], [c["nmae"] for c in p], "s--",
                color="tab:blue", ms=3, label="direct sparse polynomial (OMP)")
        dep = d[reg]["deployed"]
        ax.plot([dep["flops"]], [dep["nmae"]], "*", color="k", ms=11,
                label=f"deployed ({dep['k']} terms)")
        ax.set_xscale("log")
        ax.set_xlabel("multiply–accumulate operations per call")
        ax.set_ylabel("policy imitation nMAE (% of 12 V)" if reg == "MP" else "")
        ax.set_title(f"{reg} regime", fontsize=8)
        ax.legend(loc="upper right")
    save(fig, "Fig_Complexity.pdf")


# ------------------------------------------------------------------ Fig C
def fig_error_decomposition():
    m = json.load(open(os.path.join(RES, "openloop_metrics.json")))
    sw = json.load(open(os.path.join(RES, "sparsity_sweep.json")))
    labels = ["spline KAN", "auto-symbolic\n(raw)", "+ coefficient\nrefit",
              "+ shape\nconstraint", "deployed\n(24 terms)"]
    fig, ax = plt.subplots(figsize=(3.5, 2.3))
    w = 0.38
    for i, reg in enumerate(("MP", "NMP")):
        v = [m[reg]["kan_spline"]["nmae_pct_of_range"],
             m[reg]["symbolic_raw"]["nmae_pct_of_range"],
             m[reg]["symbolic_refit"]["nmae_pct_of_range"],
             m[reg]["symbolic_refit_shape_constrained"]["nmae_pct_of_range"],
             sw[reg]["deployed"]["nmae"]]
        ax.bar(np.arange(len(v)) + (i - 0.5) * w, v, w,
               label=reg, color=["tab:blue", "crimson"][i], alpha=0.85)
    ax.set_xticks(np.arange(len(labels)))
    ax.set_xticklabels(labels, fontsize=5.5)
    ax.set_ylabel("nMAE (% of 12 V)")
    ax.legend()
    save(fig, "Fig_ErrorDecomposition.pdf")


# ------------------------------------------------------------------ Fig D
def fig_staircase(regime="NMP"):
    fig, ax = plt.subplots(2, 1, figsize=(3.5, 3.0), sharex=True)
    for n in ("LTV-MPC", "Symbolic KAN", "Gain-scheduled LQR"):
        d = load_traj("S2", regime, n)
        if d is None:
            continue
        ax[0].plot(d["t"], d["x"][:, 0], label=n, **STYLE[n])
        ax[1].plot(d["t"], d["x"][:, 1], **STYLE[n])
    ax[0].plot(d["t"], d["ref"][:, 0], color="gray", ls=":", lw=0.8, label="reference")
    ax[1].plot(d["t"], d["ref"][:, 1], color="gray", ls=":", lw=0.8)
    ax[0].set_ylabel(r"$h_1$ (cm)")
    ax[1].set_ylabel(r"$h_2$ (cm)")
    ax[1].set_xlabel("Time (s)")
    ax[0].legend(ncol=2, loc="best")
    fig.subplots_adjust(hspace=0.1)
    save(fig, f"Fig_Staircase_{regime}.pdf")


# ------------------------------------------------------------------ Fig E
def fig_disturbance(regime="NMP"):
    fig, ax = plt.subplots(2, 1, figsize=(3.5, 3.0), sharex=True)
    for n in ("LTV-MPC", "Symbolic KAN", "MLP (32-32)"):
        d = load_traj("S3", regime, n)
        if d is None:
            continue
        ax[0].plot(d["t"], d["x"][:, 0], label=n, **STYLE[n])
        ax[1].plot(d["t"], d["u"][:, 0], **STYLE[n])
    ax[0].axhline(d["ref"][0, 0], color="gray", ls=":", lw=0.8)
    ax[0].axvline(60.0, color="gray", lw=0.6, alpha=0.6)
    ax[1].axvline(60.0, color="gray", lw=0.6, alpha=0.6)
    ax[0].set_ylabel(r"$h_1$ (cm)")
    ax[1].set_ylabel(r"$u_1$ (V)")
    ax[1].set_xlabel("Time (s)")
    ax[0].set_xlim(40, 150)
    ax[0].legend(loc="best")
    fig.subplots_adjust(hspace=0.1)
    save(fig, f"Fig_Disturbance_{regime}.pdf")


# ------------------------------------------------------------------ Fig F
def fig_degradation():
    s = json.load(open(os.path.join(RES, "scenarios.json")))
    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.3))
    for ax, reg in zip(axes, ("MP", "NMP")):
        sw = s[reg]["S4_degradation"]["sweep"]
        for n in KEY:
            if n not in sw:
                continue
            xs = [r["degradation"] * 100 for r in sw[n]]
            ys = [abs(r["ss_err_h1_cm"]) for r in sw[n]]
            ax.plot(xs, ys, "o-", ms=3, label=n, **{k: v for k, v in STYLE[n].items() if k != "ls"},
                    ls=STYLE[n]["ls"])
        ax.set_xlabel("pump-gain degradation (%)")
        ax.set_ylabel(r"$|h_1 - h_1^{\rm ref}|$ at steady state (cm)" if reg == "MP" else "")
        ax.set_title(f"{reg} regime", fontsize=8)
        ax.legend(loc="upper left")
    save(fig, "Fig_DegradationSweep.pdf")


# ------------------------------------------------------------------ Fig G
def fig_handover():
    p = os.path.join(TRAJ, "S5_handover.npz")
    if not os.path.exists(p):
        return
    d = np.load(p)
    fig, ax = plt.subplots(3, 1, figsize=(3.5, 4.0), sharex=True)
    for i, lab in ((0, r"$h_1$"), (1, r"$h_2$")):
        ax[0].plot(d["t"], d["x"][:, i], label=lab)
        ax[0].plot(d["t"], d["ref"][:, i], ls=":", lw=0.8, color="gray")
    ax[0].set_ylabel("levels (cm)")
    ax[0].legend(ncol=2)
    ax[1].plot(d["t"], d["u"][:, 0], label=r"$u_1$")
    ax[1].plot(d["t"], d["u"][:, 1], label=r"$u_2$")
    ax[1].set_ylabel("inputs (V)")
    ax[1].legend(ncol=2)
    ax[2].plot(d["t"], d["gamma_sum"], color="k")
    ax[2].axhline(1.0, color="crimson", ls="--", lw=0.8)
    ax[2].set_ylabel(r"$\gamma_1+\gamma_2$")
    ax[2].set_xlabel("Time (s)")
    fig.subplots_adjust(hspace=0.12)
    save(fig, "Fig_Handover.pdf")


# ------------------------------------------------------------------ Fig H
def fig_roa():
    st = json.load(open(os.path.join(RES, "stability.json")))
    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.6))
    for ax, reg in zip(axes, ("MP", "NMP")):
        roa = st[reg].get("roa_estimate")
        if roa is None:
            continue
        g = np.array(roa["grid_cm"])
        ok = np.array(roa["converged"], dtype=float)
        ax.pcolormesh(g, g, ok.T, cmap="Greens", vmin=0, vmax=1.4, shading="nearest")
        ax.set_xlabel(r"$h_1(0)$ (cm)")
        ax.set_ylabel(r"$h_2(0)$ (cm)" if reg == "MP" else "")
        ax.set_title(f"{reg}: converged fraction "
                     f"{roa['converged_fraction']*100:.0f}%", fontsize=8)
        ax.grid(False)
    save(fig, "Fig_ROA.pdf")


# ------------------------------------------------------------------ Fig I
def fig_signflip():
    a = json.load(open(os.path.join(RES, "signflip_analysis.json")))
    c = a["original_dataset_conditioning"]
    fig, ax = plt.subplots(1, 2, figsize=(7.0, 2.3))
    sv = np.array(c["singular_values"])
    sv = np.maximum(sv, 1e-18)
    ax[0].semilogy(range(1, len(sv) + 1), sv / sv.max(), "o-", color="crimson",
                   label=f"single-trajectory set\n(rank {c['numerical_rank_of_9_columns']}/9)")
    d = np.load(os.path.join(HERE, "data", "dataset_MP.npz"), allow_pickle=True)
    F = d["feat"]
    Fa = np.hstack([F, np.ones((len(F), 1))])
    sv2 = np.linalg.svd(Fa - Fa.mean(0), compute_uv=False)
    ax[0].semilogy(range(1, len(sv2) + 1), sv2 / sv2.max(), "s--", color="tab:blue",
                   label="excited design (rank 9/9)")
    ax[0].set_xlabel("index")
    ax[0].set_ylabel("normalised singular value")
    ax[0].set_ylim(1e-18, 3)
    ax[0].legend(loc="lower left")

    j = a["constrained_refit_on_revised_dataset"]["jitter_seed_sensitivity"]
    names = {"ORIGINAL-single-trajectory": "single trajectory", "MP": "excited (MP)",
             "NMP": "excited (NMP)"}
    xs, med, lo, hi, frac = [], [], [], [], []
    for i, (k, lab) in enumerate(names.items()):
        p = j[k]["pump2"]
        xs.append(lab)
        med.append(p["coef_on_e_median"])
        lo.append(p["coef_on_e_min"]); hi.append(p["coef_on_e_max"])
        frac.append(p["wrong_sign_frac"])
    xi = np.arange(len(xs))
    ax[1].errorbar(xi, med, yerr=[np.array(med) - np.array(lo), np.array(hi) - np.array(med)],
                   fmt="o", color="crimson", capsize=3)
    ax[1].axhline(0.0, color="k", lw=0.8)
    ax[1].set_yscale("symlog", linthresh=1e-2)
    ax[1].set_xticks(xi)
    ax[1].set_xticklabels(xs, fontsize=6)
    ax[1].set_ylabel(r"fitted coefficient on $e_2$")
    # one row of labels above the panel: anchored to the axes, so they can collide
    # with neither the error bars nor the tick labels whatever the data do
    for i, f in enumerate(frac):
        ax[1].annotate(f"wrong sign, {f*100:.0f}% of seeds", (xi[i], 1.0),
                       xycoords=("data", "axes fraction"),
                       textcoords="offset points", xytext=(0, 4),
                       ha="center", va="bottom", fontsize=5)
    # the right panel's ylabel collides with the left panel's spine at the default spacing
    fig.subplots_adjust(wspace=0.30)
    save(fig, "Fig_SignFlip.pdf")


def main():
    print("generating figures ...", flush=True)
    for f, args in ((fig_tracking, ("NMP",)), (fig_tracking, ("MP",)),
                    (fig_complexity, ()), (fig_error_decomposition, ()),
                    (fig_staircase, ("NMP",)), (fig_disturbance, ("NMP",)),
                    (fig_degradation, ()), (fig_handover, ()), (fig_roa, ()),
                    (fig_signflip, ())):
        try:
            f(*args)
        except Exception as exc:
            print(f"  !! {f.__name__}{args} failed: {type(exc).__name__}: {exc}", flush=True)


if __name__ == "__main__":
    main()
