
/*
Auto-generated by CVXPYgen on January 03, 2026 at 23:30:15.
Content: Declarations for Python binding with pybind11.
*/

// User-defined parameters
struct CPG_Params_cpp_t {
    std::array<double, 4> ref;
    std::array<double, 4> x0;
    std::array<double, 16> A;
    std::array<double, 8> B;
    std::array<double, 4> d;
};

// Flags for updated user-defined parameters
struct CPG_Updated_cpp_t {
    bool ref;
    bool x0;
    bool A;
    bool B;
    bool d;
};

// Primal solution
struct CPG_Prim_cpp_t {
    std::array<double, 124> x;
    std::array<double, 60> u;
};

// Dual solution
struct CPG_Dual_cpp_t {
    std::array<double, 4> d0;
    std::array<double, 4> d1;
    std::array<double, 2> d2;
    std::array<double, 2> d3;
    std::array<double, 4> d4;
    std::array<double, 2> d5;
    std::array<double, 2> d6;
    std::array<double, 4> d7;
    std::array<double, 2> d8;
    std::array<double, 2> d9;
    std::array<double, 4> d10;
    std::array<double, 2> d11;
    std::array<double, 2> d12;
    std::array<double, 4> d13;
    std::array<double, 2> d14;
    std::array<double, 2> d15;
    std::array<double, 4> d16;
    std::array<double, 2> d17;
    std::array<double, 2> d18;
    std::array<double, 4> d19;
    std::array<double, 2> d20;
    std::array<double, 2> d21;
    std::array<double, 4> d22;
    std::array<double, 2> d23;
    std::array<double, 2> d24;
    std::array<double, 4> d25;
    std::array<double, 2> d26;
    std::array<double, 2> d27;
    std::array<double, 4> d28;
    std::array<double, 2> d29;
    std::array<double, 2> d30;
    std::array<double, 4> d31;
    std::array<double, 2> d32;
    std::array<double, 2> d33;
    std::array<double, 4> d34;
    std::array<double, 2> d35;
    std::array<double, 2> d36;
    std::array<double, 4> d37;
    std::array<double, 2> d38;
    std::array<double, 2> d39;
    std::array<double, 4> d40;
    std::array<double, 2> d41;
    std::array<double, 2> d42;
    std::array<double, 4> d43;
    std::array<double, 2> d44;
    std::array<double, 2> d45;
    std::array<double, 4> d46;
    std::array<double, 2> d47;
    std::array<double, 2> d48;
    std::array<double, 4> d49;
    std::array<double, 2> d50;
    std::array<double, 2> d51;
    std::array<double, 4> d52;
    std::array<double, 2> d53;
    std::array<double, 2> d54;
    std::array<double, 4> d55;
    std::array<double, 2> d56;
    std::array<double, 2> d57;
    std::array<double, 4> d58;
    std::array<double, 2> d59;
    std::array<double, 2> d60;
    std::array<double, 4> d61;
    std::array<double, 2> d62;
    std::array<double, 2> d63;
    std::array<double, 4> d64;
    std::array<double, 2> d65;
    std::array<double, 2> d66;
    std::array<double, 4> d67;
    std::array<double, 2> d68;
    std::array<double, 2> d69;
    std::array<double, 4> d70;
    std::array<double, 2> d71;
    std::array<double, 2> d72;
    std::array<double, 4> d73;
    std::array<double, 2> d74;
    std::array<double, 2> d75;
    std::array<double, 4> d76;
    std::array<double, 2> d77;
    std::array<double, 2> d78;
    std::array<double, 4> d79;
    std::array<double, 2> d80;
    std::array<double, 2> d81;
    std::array<double, 4> d82;
    std::array<double, 2> d83;
    std::array<double, 2> d84;
    std::array<double, 4> d85;
    std::array<double, 2> d86;
    std::array<double, 2> d87;
    std::array<double, 4> d88;
    std::array<double, 2> d89;
    std::array<double, 2> d90;
};

// Solver information
struct CPG_Info_cpp_t {
    double obj_val;
    int iter;
    char* status;
    double pri_res;
    double dua_res;
    double time;
};

// Solution and solver information
struct CPG_Result_cpp_t {
    CPG_Prim_cpp_t prim;
    CPG_Dual_cpp_t dual;
    CPG_Info_cpp_t info;
};

// Main solve function
CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp);
